import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
        style={{ 
          background: "var(--color-bg-main)", 
          color: "var(--color-text-main)", 
          minHeight: "100vh" 
        }}
      >
        <nav style={{ 
          display: "flex", 
          justifyContent: "center", 
          gap: 32, 
          padding: "1.5rem 0", 
          background: "var(--color-bg-secondary)", 
          borderRadius: "0 0 1rem 1rem", 
          marginBottom: 32 
        }}>
          <a href="/about" style={{ color: "var(--color-primary)", fontWeight: 600, textDecoration: "none" }}>About</a>
          <a href="/project" style={{ color: "var(--color-primary)", fontWeight: 600, textDecoration: "none" }}>Project</a>
          <a href="/education" style={{ color: "var(--color-primary)", fontWeight: 600, textDecoration: "none" }}>Education</a>
          <a href="/blog" style={{ color: "var(--color-primary)", fontWeight: 600, textDecoration: "none" }}>Blog</a>
        </nav>
        {children}
      </body>
    </html>
  );
}